CREATE TYPE public.app_role AS ENUM ('admin','adviser','teacher','student','parent');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, full_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own profile" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "Create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "Update own profile" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own role" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
CREATE TABLE public.students (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_number text NOT NULL UNIQUE, full_name text NOT NULL, section_name text NOT NULL, user_id uuid, parent_id uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.students TO authenticated;
GRANT ALL ON public.students TO service_role;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff or linked student or parent reads students" ON public.students FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'adviser') OR public.has_role(auth.uid(),'teacher') OR user_id = auth.uid() OR parent_id = auth.uid());
CREATE POLICY "Admins manage students" ON public.students FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject text NOT NULL, section_name text NOT NULL, teacher_name text NOT NULL, room_name text NOT NULL, day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 6), start_time time NOT NULL, end_time time NOT NULL, CHECK(start_time < end_time));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.schedules TO authenticated;
GRANT ALL ON public.schedules TO service_role;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Members read schedules" ON public.schedules FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage schedules" ON public.schedules FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.syllabus (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject text NOT NULL, section_name text NOT NULL, teacher_name text NOT NULL, overview text NOT NULL DEFAULT '', topics text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.syllabus TO authenticated;
GRANT ALL ON public.syllabus TO service_role;
ALTER TABLE public.syllabus ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Members read syllabus" ON public.syllabus FOR SELECT TO authenticated USING (true);
CREATE POLICY "Staff manage syllabus" ON public.syllabus FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'teacher')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'teacher'));
CREATE TABLE public.grade_uploads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), file_name text NOT NULL, subject text NOT NULL, section_name text NOT NULL, uploaded_by uuid NOT NULL, uploaded_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved')));
GRANT SELECT, INSERT, UPDATE ON public.grade_uploads TO authenticated;
GRANT ALL ON public.grade_uploads TO service_role;
ALTER TABLE public.grade_uploads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff read uploads" ON public.grade_uploads FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'adviser') OR uploaded_by = auth.uid());
CREATE POLICY "Teachers upload grades" ON public.grade_uploads FOR INSERT TO authenticated WITH CHECK (uploaded_by = auth.uid() AND (public.has_role(auth.uid(),'teacher') OR public.has_role(auth.uid(),'admin')));
CREATE POLICY "Advisers approve uploads" ON public.grade_uploads FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'adviser') OR public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'adviser') OR public.has_role(auth.uid(),'admin'));
CREATE TABLE public.grades (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), upload_id uuid NOT NULL REFERENCES public.grade_uploads(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES public.students(id), subject text NOT NULL, prelim numeric(5,2) NOT NULL CHECK(prelim BETWEEN 0 AND 100), midterm numeric(5,2) NOT NULL CHECK(midterm BETWEEN 0 AND 100), final numeric(5,2) NOT NULL CHECK(final BETWEEN 0 AND 100), computed_grade numeric(5,2) GENERATED ALWAYS AS (round((prelim + midterm + final) / 3, 2)) STORED, UNIQUE(upload_id, student_id));
GRANT SELECT, INSERT ON public.grades TO authenticated;
GRANT ALL ON public.grades TO service_role;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff and approved linked viewers read grades" ON public.grades FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.grade_uploads u JOIN public.students s ON s.id = grades.student_id WHERE u.id = grades.upload_id AND (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'adviser') OR u.uploaded_by = auth.uid() OR (u.status = 'approved' AND (s.user_id = auth.uid() OR s.parent_id = auth.uid())))));
CREATE POLICY "Teachers insert own uploaded grades" ON public.grades FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.grade_uploads u WHERE u.id = upload_id AND u.uploaded_by = auth.uid() AND u.status = 'pending'));
CREATE TABLE public.document_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES public.students(id), requested_by uuid NOT NULL, document_type text NOT NULL, status text NOT NULL DEFAULT 'pending', requested_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.document_requests TO authenticated;
GRANT ALL ON public.document_requests TO service_role;
ALTER TABLE public.document_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Requesters and staff read requests" ON public.document_requests FOR SELECT TO authenticated USING (requested_by = auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY "Linked users create requests" ON public.document_requests FOR INSERT TO authenticated WITH CHECK (requested_by = auth.uid() AND EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND (s.user_id = auth.uid() OR s.parent_id = auth.uid())));
CREATE POLICY "Admins update requests" ON public.document_requests FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE FUNCTION public.prevent_schedule_conflict() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS (SELECT 1 FROM public.schedules s WHERE s.id <> NEW.id AND s.day_of_week = NEW.day_of_week AND NEW.start_time < s.end_time AND NEW.end_time > s.start_time AND (s.room_name = NEW.room_name OR s.teacher_name = NEW.teacher_name OR s.section_name = NEW.section_name)) THEN RAISE EXCEPTION 'Schedule conflict: room, teacher, or section is already booked'; END IF; RETURN NEW; END $$;
CREATE TRIGGER check_schedule_conflict BEFORE INSERT OR UPDATE ON public.schedules FOR EACH ROW EXECUTE FUNCTION public.prevent_schedule_conflict();